# -*- coding: utf-8 -*-
"""Text-Summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UV8izLMr9f-TFPttWENcvckf-jLZgY4r
"""

# Calling transformers from hugging face : WHere there are many trained transformer are there
!pip install transformers accelerate datasets #accelerate to speed up training process

from huggingface_hub import notebook_login
notebook_login()

"""#Parquet-based replacement called 'Awesome075/multi_news_parquet': Updation in hugging face original we were using 'multi_news'"""

#fine tune this transformer for smaller datasets
# We are using t5: small-version
from datasets import load_dataset
mutlinews=load_dataset('Awesome075/multi_news_parquet', split='test') #Already Split

mutlinews.to_pandas() # To see datsets how it look-like

#Becz we are training our model so we can't do web scrapping here not using them
# Here we are trying to extract the news from diff site as they have diff thought then we are using{quillbot} to summarize it.
# Each model has own embedding sys in which they take arguments :
#      Autotokenizer: processing of data as per 't5-small' required

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('t5-small')#i/p & positional embedding both

# Testing & Train split
# train-part is to large therefor we are split test-part
multi_news=mutlinews.train_test_split(test_size=.2)

#Processing Function
#Beyound-value is cutoof by truncation
prefix='summarize:'
def process_function(examples):
  inputs= [prefix+ doc for doc in examples['document']] # prefixed with "summarize" in doc
  model_inputs= tokenizer(inputs, max_length= 1024, truncation= True) #the tokenizer cuts off extra tokens so the sequence fits within max_length
  labels= tokenizer(text= examples['summary'], max_length= 128, truncation= True)
  model_inputs['labels']= labels['input_ids'] #Useful for supervised learning input_ids are the numerical token representations of the text.
  return model_inputs

tokenized_multi_news=multi_news.map(process_function, batched=True)

# DataCollatorForSeq2Seq specifically works with Seq2Seq models (like T5 or BART) and ensures correct padding for both input and target sequences.

# AutoModelForSeq2Seq is a general class for loading any pre-trained sequence-to-sequence model.LM:Language-model

#Seq2SeqTrainerArguments: elps set up training for models like T5 or BART

#Seq2SeqTrainer is a specialized version of Trainer for Seq2Seq models.
#It automates training, evaluation, and saving of sequence-to-sequence models.

#setting-up Models
from transformers import DataCollatorForSeq2Seq, AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer
data_collector= DataCollatorForSeq2Seq(tokenizer=tokenizer, model='t5_small') #data_collator
model=AutoModelForSeq2SeqLM.from_pretrained('t5-small', force_download=True)

#Hyperparam tuning
training_args= Seq2SeqTrainingArguments(
    output_dir='./results',
    eval_strategy='epoch',
    learning_rate=2e-5,
    per_device_train_batch_size=10,
    per_device_eval_batch_size=10,
    weight_decay=.01, #Regularization-Technique
    save_total_limit=3, # Check-pt Saving
    num_train_epochs=10,
    fp16=True, #mixed-precision training
    report_to = 'none'
)

## fp16 (Half-Precision Floating Point - 16-bit) enables mixed-precision training, where certain computations use 16-bit floating points (FP16)
# instead of the standard 32-bit (FP32)
## This prevents logging to platforms like WandB (Weights & Biases), TensorBoard, or MLflow.

# Training-our model
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset= tokenized_multi_news['train'],
    eval_dataset= tokenized_multi_news['test'],
    #tokenizer= tokenizer,
    data_collator=data_collector,
)

trainer.train()

text="""
Transformer is a neural network architecture used for performing machine learning tasks particularly in natural language processing (NLP) and computer vision. In 2017 Vaswani et al. published a paper ” Attention is All You Need” in which the transformers architecture was introduced. The article explores the architecture, workings and applications of transformers.

Need For Transformers Model in Machine Learning
Transformer Architecture is a model that uses self-attention to transform one whole sentence into a single sentence. This is useful where older models work step by step and it helps overcome the challenges seen in models like RNNs and LSTMs. Traditional models like RNNs (Recurrent Neural Networks) suffer from the vanishing gradient problem which leads to long-term memory loss. RNNs process text sequentially meaning they analyze words one at a time.

For example, in the sentence: “XYZ went to France in 2019 when there were no cases of COVID and there he met the president of that country” the word “that country” refers to “France”.


However RNN would struggle to link “that country” to “France” since it processes each word in sequence leading to losing context over long sentences. This limitation prevents RNNs from understanding the full meaning of the sentence.


While adding more memory cells in LSTMs (Long Short-Term Memory networks) helped address the vanishing gradient issue they still process words one by one. This sequential processing means LSTMs can’t analyze an entire sentence at once.

For instance the word “point” has different meanings in these two sentences:

“The needle has a sharp point.” (Point = Tip)
“It is not polite to point at people.” (Point = Gesture)
Traditional models struggle with this context dependence, whereas, Transformer model through its self-attention mechanism, processes the entire sentence in parallel addressing these issues and making it significantly more effective at understanding context.

Architecture and Working of Transformers
1. Positional Encoding
Unlike RNNs transformers lack an inherent understanding of word order since they process data in parallel. To solve this Positional Encodings are added to token embeddings providing information about the position of each token within a sequence.

2. Position-wise Feed-Forward Networks
The Feed-Forward Networks consist of two linear transformations with a ReLU activation. It is applied independently to each position in the sequence.

This transformation helps refine the encoded representation at each position.

3. Attention Mechanism
The attention mechanism allows transformers to determine which words in a sentence are most relevant to each other. This is done using a scaled dot-product attention approach:

1. Each word in a sequence is mapped to three vectors:

3. These scores determine how much attention each word should pay to others.

Multi-Head Attention
Instead of using a single attention mechanism transformers apply multi-head attention where multiple attention layers run in parallel. This enables the model to capture different types of relationships within the input.

4. Encoder-Decoder Architecture
The encoder-decoder structure is key to transformer models. The encoder processes the input sequence into a vector, while the decoder converts this vector back into a sequence. Each encoder and decoder layer includes self-attention and feed-forward layers. In the decoder, an encoder-decoder attention layer is added to focus on relevant parts of the input.
"""

#Tokenization for our values
input_ids = tokenizer(text, max_length=128, truncation=True, return_tensors='pt').input_ids
#pytorch tensor #Its return whole dict but to get input_ids we need to explitily mention it
input_ids =input_ids.to('cuda') #All data transferes to GPU-Part
#beam search decoding with 5 beams, meaning the model explores multiple possible sequences and selects the most likely one
# It controls the number of beams in beam search for decoding

import torch
with torch.no_grad():
  if model.device.type == 'cuda':
    output= model.generate(input_ids, max_length=139, num_beams=5)
summary_ids= output[0].tolist() # Summary encoded form

#decode
summary= tokenizer.decode(summary_ids, skip_special_tokens= True)
print(summary)

ref_summary="""
             Transformer is a neural network architecture used in machine learning, particularly in natural language processing and computer vision.
            Introduced in 2017 by Vaswani et al., Transformer uses self-attention to transform a whole sentence into a single sentence, overcoming challenges
             faced by traditional models like Recurrent Neural Networks (RNNs) and Long Short-Term Memory Networks (LSTMs). Transformers process the entire sentence in parallel, addressing the vanishing gradient problem and enabling better understanding of context.

Turbomotives have four main architectures: Positional Encoding, Position-wise Feed-Forward Networks, Attention Mechanism, and Encoder-Decoder Architecture. Positional Encoding adds information about the position of each token within a sequence, while Feed-Forward Networks refine the encoded representation at each position. Attention Mechanism determines the most relevant words in a sentence using a scaled dot-product approach. Multi-Head Attention allows the model to capture different types of relationships within the input.
""" #ref-summary from Quilblot to compare

!pip install rouge

# How's summary frompredicated to actual one we use rouge metrics
from rouge import Rouge
rouge= Rouge()
scores= rouge.get_scores(summary, ref_summary)
scores #{'rouge-1': {'r': value(recall), 'p': (precision), 'f': (f1-score)}}
#r-1:  long sequence matching with our :- 0.2  not so good
#r-2: check bigram tpow words amtching same
#r-l: refer to 1 but its regardless of the sequence

#We can improve our model by providing it ore text
trainer.save_model()

model.save_pretrained('Summarizer')#summarze_model saved